# Generated by Django 4.2.5 on 2023-09-13 14:18

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content_1', ckeditor.fields.RichTextField(null=True)),
                ('content_2', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
        ),
    ]
